#!/bin/bash
if [ $# -eq 0 ] ; then
        echo "backup_retrieve directory (end with /) description"
        exit 0
fi

echo $1 " " $2

if [ $# -eq 1 ]; then
	dsmc retrieve -se=fengz03 $1 -sub=yes
fi 


