#!/bin/bash
if [ $# -ne 2 ] ; then
        echo "bamtofasta_dir indir outdir"
        exit 0
fi

mkdir -p $2

ls $1/*.bam | awk -v indir=$1 -v outdir=$2 -v hpcopt="submitjob 1 -c 1 -m 4 -P acc_LymeMIND -q premium" '{cmd=hpcopt" bamtofasta "$0" "outdir"/";gsub(indir"/","",$0); gsub("/","",$0);gsub(".bam",".fasta",$0); cmd=cmd$0;print cmd; system(cmd)}'




