#!/bin/bash
if [ $# -ne 4 ] ; then
        echo "canu_pacbio_dir inputdir outputdir genomesize hpcdir"
        exit 0
fi
indir=$1
outdir=$2
gsize=$3
hpcdir=$4

mkdir -p $outdir

for infile in $(ls $indir | egrep '*.(fa|fq|fastq|fasta|fastq.gz|fasta.gz)$'); do
	jname=${infile%.*}
	cur_outdir=$outdir/$jname
	mkdir -p $cur_outdir
	hpc="submitjob -w 6 -c 16 -m 32 -j $jname -o $hpcdir"
	cmd=$hpc" canu stopOnReadQuality=false useGrid=false gnuplotTested=true -p $jname -d $cur_outdir genomeSize=$gsize -pacbio-raw $indir/$infile"
	$cmd
done

#ls $1 | egrep '*.(fa|fq|fastq|fasta|fastq.gz|fasta.gz)$' | awk -v gsize=$3 -v indir=$1 -v outdir=$2 -v hpcopt="submitjob 12 -c 4 -m 32 -P acc_LymeMIND -q premium" '{outprefix=$0; gsub(".(fa|fq|fastq|fasta|fastq.gz|fasta.gz)","",outprefix);cmd=hpcopt" canu stopOnReadQuality=false useGrid=false -d "outdir"/"outprefix" -p "outprefix" genomeSize="gsize" -pacbio-raw "indir"/"$0; print cmd; system(cmd)}'





