#!/bin/bash
if [ "$#" -ne 3 ]; then
        echo "ccs_dir indir outdir nthread"
        exit 0
fi

indir=$1
outdir=$2
nthread=$3
mkdir -p $outdir

for bamfile in $(ls $indir | grep ".bam$" ); do
	ccsfile=${bamfile%.*}_ccs.bam
	reportfile=${bamfile%.*}_report.txt
	submitjob 6 -c $nthread -m 16 -P acc_LymeMIND -q premium ccs --richQVs --force --reportFile $outdir/$reportfile $indir/$bamfile $outdir/$ccsfile
done


