#!/bin/bash
if [ $# -ne 1 ] ; then
        echo "check_all_snv snp_file"
        exit 0
fi

awk '
BEGIN{
	n_snv = 0; n_var = 0;
}
{
	if ($2 != "." && $3 != "."){
		n_snv++;
	}
	n_var++;
}
END{
	if(n_snv == n_var){ 
		print 1
	}else{
		print 0
	}
}' $1

