#!/bin/bash
if [ $# -ne 2 ] ; then
        echo "cmpgenome_trim out_coords_file out_coords_trim_file"
        exit 0
fi

out_coords_file=$1
out_coords_trim_file=$2

#out_coords_trim_file=${out_coords_file%.*}.trim.coords
awk -F "\t" '{
	if (FNR == 1){
		rstart = ($1 < $2 ? $1 : $2)
		rend = ($1 > $2 ? $1 : $2)
		qstart = ($3 < $4 ? $3 : $4)
		qend = ($3 > $4 ? $3 : $4)
	}else{
		if ($1 < rstart){ rstart = $1 }
		if ($2 < rstart){ rstart = $2 }
		if ($1 > rend){ rend = $1 }
		if ($2 > rend){ rend = $2 }
		
		if ($3 < qstart){ qstart = $3 }
		if ($4 < qstart){ qstart = $4 }
		if ($3 > qend){ qend = $3 }
		if ($4 > qend){ qend = $4}
	}	
}END{print "rstart\t"rstart; print "rend\t"rend; print "qstart\t"qstart; print "qend\t"qend}' $out_coords_file > $out_coords_trim_file.range

rstart=$(grep -w rstart $out_coords_trim_file.range | awk '{print $2}')
rend=$(grep -w rend $out_coords_trim_file.range | awk '{print $2}')
qstart=$(grep -w qstart $out_coords_trim_file.range | awk '{print $2}')
qend=$(grep -w qend $out_coords_trim_file.range | awk '{print $2}')

awk -F "\t" -v rstart=$rstart -v rend=$rend -v qstart=$qstart -v qend=$qend '{
	print $1-rstart+1 "\t" $2-rstart+1 "\t" $3-qstart+1 "\t" $4-qstart+1 "\t" $5"\t"$6"\t"$7"\t"rend-rstart+1"\t"qend-qstart+1"\t"$10"\t"$11
}' $out_coords_file > $out_coords_trim_file



