#!/bin/bash
if [ $# -ne 5 ] ; then
        echo "cmpgenome_dir indir reffile outdir nthread logdir"
        exit 0
fi

mkdir -p $3

indir=$1
reffile=$2
outdir=$3
nthread=$4
logdir=$5

for infile in $(ls $indir | egrep ".fna$|.fasta$|.fa$"); do
	outprefix=$outdir/${infile%.*}
	jobname=${infile%.*}
	submitjob -w 1 -c $nthread -m 4 -o $logdir -j $jobname cmpgenome $indir/$infile $reffile $outprefix
done



