#!/bin/bash
if [ $# -ne 3 ] ; then
        echo "cmpgenome_dir indir reffile outdir"
        exit 0
fi


mkdir -p $3

#ls $1 | egrep ".fna$|.fasta$|.fa$" | awk -v indir=$1 -v reffile=$2 -v outdir=$3 '{cmd="cmpgenome "indir"/"$0" "reffile" "outdir;gsub(".fasta","",$0);cmd=cmd"/"$0;print cmd; system(cmd)}'

ls $1 | egrep ".fna$|.fasta$|.fa$" | awk -v indir=$1 -v reffile=$2 -v outdir=$3 -v hpcopt="submitjob 0.5 -c 1 -m 4 -P acc_LymeMIND -q premium" '{cmd=hpcopt" cmpgenome "indir"/"$0" "reffile" "outdir;gsub(".fasta","",$0);cmd=cmd"/"$0;print cmd; system(cmd)}'

