#!/bin/bash
if [ $# -ne 2 ] ; then
        echo "download_sra accession_list outdir"
        exit 0
fi

accession_list=$1
outdir=$2


for run_id in $(cat $accession_list); do 
	curpath=$(srapath $run_id)
	echo $curpath
	wget -c $curpath -O $outdir/$run_id.sra
done


#wget -c ftp://ftp-trace.ncbi.nih.gov/sra/sra-instant/reads/ByRun/sra/$srrtype/$srrnum/$srrfile/${srrfile}.sra -O $2/${srrfile}.sra


