#!/bin/bash
if [ $# -ne 2 ] ; then
        echo "download_sra accession_list outdir"
        exit 0
fi

file=$1
files=`cat $file`
files=($(echo $files | tr -d "\n"))

for srrfile in ${files[@]}
do
echo ${srrfile}
srrnum=${srrfile:0:6}
srrtype=${srrfile:0:3}
wget -c ftp://ftp-trace.ncbi.nih.gov/sra/sra-instant/reads/ByRun/sra/$srrtype/$srrnum/$srrfile/${srrfile}.sra -O $2/${srrfile}.sra

done

