#!/bin/bash
if [ $# -ne 2 ] ; then
        echo "download_hdf5 accession_list outdir"
        exit 0
fi

mkdir -p $2

run_ids=$(cat $1)
for run_id in $run_ids; do
	url=$(srapath $run_id -f names --raw -p typ=srapub_files -p accept-proto=https | grep srapub_files |  cut -d '|' -f8)
	wget -c --no-check-certificate $url -O $2/$run_id.tgz
done



#awk -v outdir=$2 '{cmd="wget --no-check-certificate http://sra-download.ncbi.nlm.nih.gov/srapub_files/"$1"_"$1"_hdf5.tgz -O "outdir"/"$1".tgz"; system(cmd);}' $1


