#!/bin/bash
if [ "$#" -ne 1 ]; then
        echo "encode_dir indir"
        exit 0
fi


ls $1 | egrep ".m5$" | awk -v indir=$1 -v reffile=$2 '{cmd="igda encode -t "indir"/"$0; gsub(".m5",".encode",$0); cmd=cmd" "indir"/"$0; print cmd; system(cmd)}'





#if [ "$#" -eq 4 ] ; then
#	cat $4 | awk -v indir=$1 -v refile=$2 -v outdir=$3 -v hpcopt="submitjob 2 -c 8 -m 6 -P acc_LymeMIND -q premium" '{cmd=hpcopt" pbalign --minLength=1000 --minAccuracy=75 --algorithm=\"blasr\" --algorithmOptions=\"--clipping hard --bestn 1\" "indir"/"$0".bam "refile" "outdir"/"$0".bam" ; print cmd; system(cmd) }'
#fi


