#!/bin/bash
if [ "$#" -ne 3 ]; then
        echo "exclude_loci loci_list in_file(column 1 is locus) out_file"
        exit 0
fi

loci_list=$1
in_file=$2
out_file=$3

awk -F "\t" '{
	if (NR==FNR){
		methyl_loci[$1]=1
	}else{
		if (methyl_loci[int($1/4)]!=1){
			print
		}
	}
	
}' $loci_list $in_file > $out_file









