#!/bin/bash
tc=1
if [ "$#" -ne 3 ]; then
	if [ "$#" -eq 4 ]; then
		tc=$4
	else
		echo "exclude_loci loci_list in_file out_file [column,default=1]"
        	exit 0
	fi
fi

loci_list=$1
in_file=$2
out_file=$3

awk -F "\t" -v tc=$tc '{
	if (NR==FNR){
		methyl_loci[$1]=1
	}else{
		if (methyl_loci[$tc]!=1){
			print
		}
	}
	
}' $loci_list $in_file > $out_file









