#!/bin/bash
if [ "$#" -ne 4 ]; then
        echo "fasta_subseq fasta_file chr start end"
        exit 0
fi

fasta_file=$1
chr=$2
rstart=$3
rend=$4

bioawk -c fastx -v chr=$chr -v rstart=$rstart -v rend=$rend '{
	if ($name == chr){
		print ">"chr"_"rstart"_"rend
		print substr($seq, rstart, rend - rstart + 1)
	}
}' $fasta_file 


