#!/bin/bash
if [ $# -ne 2 ] ; then
        echo "fastq_dump_dir indir outdir"
        exit 0
fi

indir=$1
outdir=$2

mkdir -p $outdir

for srafile in $(ls $indir | grep .sra$);do 
	samplename=${srafile%.*}
	submitjob 4 -c 4 -m 8 -P acc_LymeMIND -q premium fastq-dump -O $outdir/$samplename $indir/$srafile
done

#ls ./$1/*.sra | awk -v outdir=$2 '{cmd="fastq-dump -O "outdir" "$0; print cmd; system(cmd)}'


