#!/bin/bash
if [ $# -ne 3 ] ; then
        echo "fastq_dump_dir indir outdir logdir"
        exit 0
fi

indir=$1
outdir=$2
logdir=$3

mkdir -p $outdir
mkdir -p $logdir

for srafile in $(ls $indir | grep .sra$);do 
	samplename=${srafile%.*}
	submitjob -w 4 -c 4 -m 8 -o $logdir -j $samplename fastq-dump -O $outdir $indir/$srafile
done

#ls ./$1/*.sra | awk -v outdir=$2 '{cmd="fastq-dump -O "outdir" "$0; print cmd; system(cmd)}'


