#!/bin/bash
if [ $# -ne 3 ] ; then
        echo "fastq2fasta_dir indir outdir logdir"
        exit 0
fi

indir=$1
outdir=$2
logdir=$3

mkdir -p $outdir

for fqfile in $(ls $indir | grep "[.fastq$|.fq$]");do
	echo $fqfile
done


