#!/bin/bash
if [ "$#" -ne 4 ]; then
        echo "fasta_subseq fasta_file chr start end"
        exit 0
fi

fasta_file=$1
chr=$2
rstart=$3
rend=$4

bioawk -c fastx -v chr=$chr -v rstart=$rstart -v rend=$rend '{
	if ($name == chr){
		#print ">"chr"_"rstart"_"rend
		cur_start = (rstart < rend ? rstart : rend)
		cur_end = (rstart >= rend ? rstart : rend)
		print ">"chr"_"cur_start"_"cur_end
		print substr($seq, cur_start, cur_end - cur_start + 1)
	}
}' $fasta_file 


