#! /bin/bash
if [ $# != 3 ]; then
	echo "file_sel file1 file2 field_id (file2 is the key list, field is the 1-based key column )"
	exit 1
fi

awk -v fid=$3 $'{
	if (NR==FNR){
		temp[$1] = 1;
	}else{
		if (temp[$fid] == 1){
			print;
		}
	}
}' $2 $1

