#!/bin/bash
if [ $# -ne 3 ] ; then
        echo "filter_pacbio_dir indir outdir logdir"
        exit 0
fi

indir=$1
outdir=$2
logdir=$3

mkdir -p $outdir

for bamdir in $(ls -d $1/*/); do
	samplename=$(basename $bamdir)
	outbam=$outdir/$samplename.bam
	cmd="submitjob -w 4 -c 1 -m 6 -j $samplename -o $logdir filter_pacbio $bamdir $outbam"
	$cmd
done



#mkdir -p $2

#ls -d $1/*/ | awk -v indir=$1 -v outdir=$2 -v hpcopt="submitjob 4 -c 1 -m 6 -P acc_LymeMIND -q premium" '{cmd=hpcopt" filter_pacbio "$0" "outdir"/";gsub(indir"/","",$0); gsub("/","",$0); cmd=cmd$0".bam";  print cmd; system(cmd)}'



