#!/bin/bash
if [ $# -ne 2 ] ; then
        echo "filter_pacbio indir(unzipped folder output by hdf5tobam) out_bam_file"
        exit 0
fi


if [ "$(ls $1 | wc -l)" == 0 ] ; then
	echo "empty folder: $1"
	exit 0
fi

indir=$1
outfile=$2

nfile=$(ls $indir/*.subreads.bam | wc -l)
if [ $nfile -ne 1 ];then
	echo "there are multiple subreads.bam files"
	exit 1
fi

bam_file=$(ls $indir/*.subreads.bam)


samtools view $bam_file | awk '
{ 	
	for(i=1;i<=NF;i++){
		if (substr($i,1,5) == "rq:f:"){
			rq = substr($i, 6, length($i));
		}
		if (substr($i,1,5) == "zm:i:"){
			zm = substr($i, 6, length($i));
		}	
	}
	if (rq>=0.75){
		print zm;
	} 
}
' > $outfile.filt_idx

bamsieve --whitelist $outfile.filt_idx $bam_file $outfile





