#!/bin/bash
if [ $# -ne 5 ] ; then
        echo "filter_snp_dir indir(snpfiles) outdir chr start end (1-based)"
        exit 0
fi

mkdir -p $2
snpfiles=$(ls $1/*.snp)
for snpfile in $snpfiles; do
	snpfile_base=$(basename $snpfile)
	echo $snpfile "$2/$snpfile_base" $3 $4 $5
	filter_snp $snpfile "$2/$snpfile_base" $3 $4 $5
done


