#!/bin/bash
if [ "$#" -ne 2 ]; then
        echo "gen_artificial_var_dir indir logdir"
        exit 0
fi

indir=$1
logdir=$2
m5files=$(ls $indir/*.m5)

#hpcopt="submitjob 1 -c 1 -m 6 -P acc_LymeMIND -q premium"
for m5file in $m5files
do
	varfile=${m5file%.*}.var
	jobname=$(basename ${m5file%.*})
	cmd="submitjob -w 1 -c 1 -m 6 -o $logdir -j $jobname gen_artificial_var $m5file $varfile"
	echo $cmd
	$cmd
done



