#!/bin/bash
if [ "$#" -ne 1 ]; then
        echo "gen_artificial_var_dir indir"
        exit 0
fi

m5files=$(ls $1/*.m5)

hpcopt="submitjob 1 -c 1 -m 6 -P acc_LymeMIND -q premium"
for m5file in $m5files
do
	varfile=${m5file%.*}.var
	cmd=$hpcopt" gen_artificial_var $m5file $varfile"
	echo $cmd
	$cmd
done



