#!/bin/bash
if [ "$#" -ne 6 ]; then
        echo "getbambyregion inbamfile outbamfile chr start end(1-based) nthread"
        exit 0
fi

inbamfile=$1
outbamfile=$2
chr=$3
start_locus=$4
end_locus=$5
nthread=$6

sam_region=$chr":"$start_locus"-"$end_locus

samtools view --threads $nthread -h -b -o $outbamfile $inbamfile $sam_region

