#!/bin/bash
if [ "$#" -ne 2 ]; then
        echo "getdepth_dir indir logdir"
        exit 0
fi

indir=$1
logdir=$2

for bamfile in $(ls $indir/*.bam);do
	sample_name=$(basename $bamfile)
	sample_name=${sample_name%.bam}
	cvgfile=$indir/$sample_name.cvg
	#cmd="submitjob -m 16 -w 8 -j $sample_name -o $logdir bamtools coverage -in $bamfile -out $cvgfile"
	cmd="submitjob -m 16 -w 16 -j $sample_name -o $logdir getdepth $bamfile $cvgfile"
	$cmd
done




