#!/bin/bash
if [ "$#" -ne 1 ]; then
        echo "getmeandepth cvgfile"
        exit 0
fi

awk 'BEGIN{cvg=0}{cvg+=$3}END{print cvg/NR}' | $1

#bamtools coverage -in $1 | awk 'BEGIN{cvg=0}{cvg+=$3}END{print cvg/NR}'


