#!/bin/bash
if [ $# -ne 4 ]; then
        echo "USAGE: getreadsbyref_dir indir(samfile) ref outdir logdir"
        exit 0
fi

indir=$1
ref=$2
outdir=$3
logdir=$4

mkdir -p $outdir
mkdir -p $logdir
for samfile in $(ls $indir/*.sam); do
	jname=$(basename ${samfile%.*})
	outfile=$outdir/${jname}.sam
	#hpc="submitjob -w 1 -c 1 -m 1 -o $logdir -j $jname"
	hpc=""
	cmd=$hpc" getreadsbyref $samfile $ref $outfile"
	echo $cmd;
	$cmd
done

#samtools view -H $samfile | egrep -w "@PG|SN:$ref" > $outfile
#samtools view $samfile | awk -v ref=$ref '{if ($3==ref) print $0}' >>$outfile


