#!/bin/bash
if [ $# -ne 2 ]; then
        echo "USAGE: getreadsbyname namefile bamfile(samfile)"
        exit 0
fi

namefile=$1
bamfile=$2
samtools view -H $bamfile
samtools view $bamfile > ${bamfile}.tmp.getreadsbyname


awk '{
	if (NR == FNR){
		name_list[$1] = 1
	}else{
		if (name_list[$1] == 1){
			print $0
		}
	}
}' $namefile ${bamfile}.tmp.getreadsbyname


