#!/bin/bash
if [ $# -ne 2 ] ; then
        echo "getuniqsnv infile(snp file of nucmer) outfile"
        exit 0
fi

awk '
{
	x[$13, $1]+=1; 
	y[$13, $1]=$2"\t"$3
} 

END{ 
	for(i in x) {
		key=i;
		gsub("\034","\t",key); 
		split(y[i], t, "\t");
		if(x[i]==1 && t[1]!="." && t[2]!="."){
			print key"\t"y[i]
		} 
	} 
}' $1 | sort -s -k1,1 -k2,2n > $2


#awk '{for(i=$1;i<=$2;i++){x[$10,i]+=1}} END{for(i in x) {key=i;gsub("\034","\t",key);print key"\t"x[i]}}' $1 | sort -s -k1,1 -k2,2n > $2



