#!/bin/bash
if [ $# -ne 3 ] ; then
        echo "hdf5tobam_dir indir (the folder containing unzipped folders output by unziphdf5) outdir logdir"
        exit 0
fi

indir=$1
outdir=$2
logdir=$3

for hdfdir in $(ls -d $indir/*/); do
	samplename=$(basename $hdfdir)
	bamdir=$outdir/$samplename
	cmd="submitjob -w 6 -c 1 -m 4 -j $samplename -o $logdir hdf5tobam $hdfdir $bamdir"
	$cmd
done
#mkdir -p $2

#ls -d $1/*/ | awk -v indir=$1 -v outdir=$2 -v hpcopt="submitjob 6 -c 1 -m 4 -P acc_LymeMIND -q premium" '{cmd=hpcopt" hdf5tobam "$0" "outdir"/";gsub(indir,"",$0);gsub("/","",$0); cmd=cmd$0;  print cmd; system(cmd)}'




