#!/bin/bash
# require bioawk
if [ "$#" -ne 3 ]; then
        echo "igda_var2vcf var_file ref_file vcf_file"
        exit 0
fi

var_file=$1
ref_file=$2
vcf_file=$3

bioawk -c fastx '{if (NR>1){print "number of refseq > 1"; exit 1}else{print $name"\t"$seq}}' $ref_file > ${vcf_file}.tmp.fasta

sort -nu -k3,3 $var_file > ${vcf_file}.tmp.var

# vcf metainfo
echo -e "##fileformat=VCFv4.2" > $vcf_file
echo -e "##fileDate=$(date)" >> $vcf_file
echo -e "##source=igda" >> $vcf_file
echo -e "##reference=$ref_file" >> $vcf_file
echo -e "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO" >> $vcf_file

# fill in data to vcf 
awk -F "\t" 'BEGIN{pre_pos = -1}{
	if (NR == FNR){
		refname = $1
		split($2, refseq, "")
	}else{
		pos = $1 + 1
		refbase = refseq[pos]
		altbase = $2
		if (refbase == altbase){
			print "refbase == altbase"
			exit 1
		}
		#refbase = "N"
		if (pos == pre_pos){
			pre_altbase = pre_altbase","altbase
		}else{
			if (FNR > 1){
				print refname"\t"pre_pos"\t.\t"pre_refbase"\t"pre_altbase"\t"100"\tPASS\t""."
			}
			pre_pos = pos
			pre_refbase = refbase
			pre_altbase = altbase
		}
	}
	
}END{ 
	print refname"\t"pre_pos"\t.\t"pre_refbase"\t"pre_altbase"\t"100"\tPASS\t""." 
}' ${vcf_file}.tmp.fasta ${vcf_file}.tmp.var >> $vcf_file

rm ${vcf_file}.tmp.fasta ${vcf_file}.tmp.var


