#!/bin/bash
if [ $# -ne 2 ] ; then
        echo "igda_mpileup_dir indir (m5files) outdir"
        exit 0
fi

indir=$1
outdir=$2

hpc="submitjob 4 -c 1 -m 16 -P acc_LymeMIND -q premium"
mkdir -p $outdir
for m5file in $(ls $indir/ | grep .m5$);do
	cur_outdir=${m5file%.m5}_pileup
	cmd=$hpc" igda_mpileup $indir/$m5file $outdir/$cur_outdir"
	echo $cmd
	$cmd
done






