#!/bin/bash
if [ $# -ne 2 ] ; then
        echo "igda_mpileup m5file outdir"
        exit 0
fi

m5file=$1
outdir=$2

mkdir -p $outdir

# count number of reads mapped to each reference
echo "count number of reads mapped to each reference"
awk '{print $6}' $m5file | sort | uniq -c > $outdir/ref_count.txt

# split m5file
echo "split m5file"
sample_id=$(basename $m5file)
sample_id=${sample_id%.*}

for ref in $(awk '{print $2}' $outdir/ref_count.txt);do
	outfile=$outdir/"tmp_"$sample_id"_"$ref".m5"
	grep -w $ref $m5file > $outfile
done

# pileup
echo "pileup"
for tmp_m5file in $(ls $outdir/*.m5);do
	outfile=$(basename ${tmp_m5file%.*}.pileup)
	outfile=$outdir/${outfile#tmp_}	
	cmd="igda pileup $tmp_m5file $outfile"
	echo $cmd
	$cmd
done

rm $outdir/tmp_*.m5






