#!/bin/bash
if [ $# -ne 3 ] ; then
        echo "igda_pipe_phase_ont indir(output of igda_pipe_detect_ont) reffile"
	exit 0
fi


indir=$1
reffile=$2

echo "indir = "$indir
echo "reffile = "$reffile

echo "Start."

echo "============= dimension reduction ==========="
igda rdim $indir/realign.encode $indir/realign.var $indir/realign.encode.rdim

echo "============= recode ==========="
igda recode $indir/realign.m5 $indir/realign.var $indir/realign.recode

echo "============= ann ==========="
ann_t=$dforest_r
ann_m=$(($ann_t+$ann_t))
ann_c=10
echo "ann_t=$ann_t, ann_m=$ann_m, ann_c=$ann_c"
igda ann -j 0.5 -c $ann_c -t $ann_t -m $ann_m  $indir/realign.recode $indir/realign.encode.rdim $indir/realign.m5 $indir/realign.var $reffile $indir/realign.ann

echo "============= test contigs ==========="
igda test_contigs $indir/realign.ann $indir/realign.recode $indir/realign.m5 $reffile

echo "============= calculate abundance ==========="
igda abundance $indir/realign.ann.tested.ft $indir/realign.recode $indir/realign.m5

echo "============= test contigs pairwisely ==========="
igda test_contigs_pairwise $indir/realign.ann.tested.ft.count $indir/realign.recode $reffile

echo "============= transitive reduction ==========="
igda tred $indir/realign.ann.tested.ft.count.ft

echo "============= assemble ==========="
igda assemble $indir/realign.ann.tested.ft.count.ft $indir/realign.ann.tested.ft.count.ft.tred.dot

echo "============= recalculate abundance ==========="
igda abundance $indir/realign.ann.tested.ft.count.ft.assembled $indir/realign.recode $indir/realign.m5

echo "Done."


