#!/bin/bash
if [ "$#" -ne 3 ]; then
	echo "igda_boosting_pred train_outdir test_file pred_file"
        exit 0
fi

train_outdir=$1
test_file=$2
pred_file=$3

xgboost $train_outdir/boosting.conf task=pred model_in=$train_outdir/boosting.model test:data=$test_file name_pred=$pred_file


