#!/bin/bash
if [ $# -ne 4 ] ; then
        echo "igda_align infile(bam or sam file) reffile contextfile outdir"
        exit 0
fi

infile=$1
reffile=$2
contextfile=$3
outdir=$4

echo "infile = "$infile
echo "reffile = "$reffile
echo "contextfile = "$contextfile
echo "outdir = "$outdir

mkdir -p $outdir

#echo "============= realign ==========="
#igda_align $aligner $infile $reffile $outdir/realign.sam $nthread

echo "============= samtom5 ==========="
igda samtom5 $infile $reffile $outdir/realign.m5

echo "============= encode ==========="
igda encode -t $outdir/realign.m5 $outdir/realign.encode

echo "============= cmpreads ==========="
igda cmpreads -l 0.5 -p 20 $outdir/realign.encode $outdir/realign.m5 $outdir/realign.cmpreads

echo "============= dforest ==========="
time igda dforest -d 10000 -r 15 $outdir/realign.encode $outdir/realign.m5 $outdir/realign.cmpreads $reffile $outdir/realign.dforest $outdir/tmp
igda filter -f 0.75 $outdir/realign.dforest $outdir/realign.dforest.f75

echo "============= detect orphan variants ==========="
igda contexteffect $outdir/realign.m5 $outdir/realign
igda detectsingle -c 1000 -f 0.01 -b 50 $outdir/realign.pileup $contextfile $outdir/realign.detectsingle
#cat $outdir/realign.detectsingle $outdir/realign.dforest.f75 | sort -s -u -k1,1n > $outdir/realign.detected
cat $outdir/realign.dforest.f75 $outdir/realign.detectsingle | sort -s -u -k1,1n > $outdir/realign.detected
igda getvar -c 0 $outdir/realign.detected $outdir/realign.var

echo "============= dimension reduction ==========="
igda rdim $outdir/realign.encode $outdir/realign.var $outdir/realign.encode.rdim

echo "============= recode ==========="
igda recode $outdir/realign.m5 $outdir/realign.var $outdir/realign.recode

echo "============= ann ==========="
igda ann -j 0.5 -c 10 -t 12 -m 30  $outdir/realign.recode $outdir/realign.encode.rdim $outdir/realign.m5 $outdir/realign.var $reffile $outdir/realign.ann

echo "============= test contigs ==========="
igda test_contigs $outdir/realign.ann $outdir/realign.recode $outdir/realign.m5 $reffile

echo "============= transitive reduction ==========="
igda tred $outdir/realign.ann.tested.ft

echo "============= assemble ==========="
igda assemble $outdir/realign.ann.tested.ft $outdir/realign.ann.tested.ft.tred.dot


