#!/bin/bash
if [ "$#" -ne 2 ]; then
        echo "igda_encode  m5file encodefile"
	echo "locus is 0-based"
        exit 0
fi

m5file=$1
encodefile=$2

awk '{
	split($17, query, "");
	split($19, ref, "");
	if (length($17) != length($19)){
		exit(1)
	}
	
	cur_locus = $8
	for (i=1; i <= length($19); i++) {
  		if (ref[i]=="A" || ref[i]=="C" || ref[i]=="G" || ref[i]=="T"){
			if (query[i] == "-"){
				
			}else{
				if (query[i] != ref[i]){
					if (query[i] == "A"){
						printf("%d\t", 4*cur_locus);
					}else{
						if (query[i] == "C"){
							printf("%d\t", 4*cur_locus+1);
						}else{
							if (query[i] == "G"){
								printf("%d\t", 4*cur_locus+2);
							}else{
								if (query[i] == "T"){
									printf("%d\t", 4*cur_locus+3);
								}else{

								}
							}
						}
					}
				}else{
				
				}
			}
			cur_locus++;
		}
	}
	
}' $m5file > $encodefile




