#!/bin/bash
if [ $# -ne 5 ] ; then
        echo "igda_align_ont_dir indir(contains bam files) reffile outdir nthread logdir"
        exit 0
fi

indir=$1
reffile=$2
outdir=$3
nthread=$4
logdir=$5

bamfiles=$(ls $indir/*.bam)

mkdir -p $outdir
mkdir -p $logdir


hpc="submitjob 6 -c $nthread -m 16 "
#hpc=""
for bamfile in $bamfiles; do
	outfile=$(basename $bamfile)
	outfile=$outdir/"${outfile%.*}".sam
	jobname=$(basename ${outfile%.*})
	hpc="submitjob -w 6 -c $nthread -m 16 -j $jobname -o $logdir"
	cmd="$hpc igda_align_pb $bamfile $reffile $outfile $nthread"
	#echo $cmd
	$cmd
done





