#!/bin/bash
if [ $# -ne 4 ] ; then
        echo "igda_mcontext m5file outdir leftlen rightlen"
        exit 0
fi

m5file=$1
outdir=$2
leftlen=$3
rightlen=$4

mkdir -p $outdir

# count number of reads mapped to each reference
echo "count number of reads mapped to each reference"
awk '{print $6}' $m5file | sort | uniq -c > $outdir/ref_count.txt

# split m5file
echo "split m5file"
split_m5_by_ref $m5file $outdir/tmp

# pileup
echo "pileup"
for tmp_m5file in $(ls $outdir/tmp/*.m5);do
	outprefix=$(basename ${tmp_m5file%.*})
	outprefix=$outdir/${outprefix#tmp_}	
	cmd="igda contexteffect -l $leftlen -r $rightlen $tmp_m5file $outprefix"
	echo $cmd
	$cmd
done

rm -rf $outdir/tmp






