#!/bin/bash
if [ $# -ne 2 ] ; then
        echo "igda_mpileup m5file outdir"
        exit 0
fi

m5file=$1
outdir=$2

mkdir -p $outdir

split_m5_by_ref $m5file $outdir/m5_split

# pileup
mkdir -p $outdir
echo "pileup"
for tmp_m5file in $(ls $outdir/m5_split/*.m5);do
	outfile=$(basename ${tmp_m5file%.*}.pileup)
	outfile=$outdir/${outfile#tmp_}	
	cmd="igda pileup $tmp_m5file $outfile"
	echo $cmd
	$cmd
done

rm -rf $outdir/m5_split






