#!/bin/bash
if [ $# -ne 3 ] ; then
        echo "minimap2_nanopore_dir ref inputdir outputdir"
        exit 0
fi

mkdir -p $3


ls $2 | egrep '*.(fa|fq|fastq|fasta|fastq.gz|fasta.gz)$' | awk -v ref=$1 -v indir=$2 -v outdir=$3 -v hpcopt="submitjob 6 -c 4 -m 16 -P acc_LymeMIND -q premium" '{
	cmd=hpcopt" minimap2 --secondary=no -ax map-ont "ref" ./"indir"/"$0" > ./"outdir"/"$0".sam"; print cmd; system(cmd);

}'




