#!/bin/bash
if [ $# -ne 4 ] ; then
        echo "minimap2_genome ref infile outfile nthread"
        exit 0
fi

#minimap2 --secondary=no -ax asm10 -t $4 $1 $2 > $3
#minimap2 -ax asm10 -t $4 $1 $2 > $3
minimap2 -ax asm20 -t $4 $1 $2 > $3


