#!/bin/bash
minmapq=0
if [ $# -ne 4 ] ; then
	if [ $# -ne 5 ];then 
        	echo "minimap2_pacbio ref infile outfile nthread [minMapQ]"
        	exit 0
	else
		minmapq=$5
	fi
fi

echo "minmapq = "$minmapq
minimap2  --secondary=no -ax map-pb -t $4 $1 $2 > "$3.tmp"

samtools view -h -q $minmapq --threads $4 -F 4079 "$3.tmp" > $3
rm "$3.tmp"


