#!/bin/bash
if [ "$#" -ne 1 ]; then
        echo "pbindex_dir indir (contain bam files)"
        exit 0
fi

bamfiles=$(ls $1/*.bam)

for bamfile in $bamfiles; do
	#echo $bamfile
	submitjob 6 -c 1 -m 8 -P acc_LymeMIND -q premium pbindex $bamfile
done

