#!/bin/bash
if [ "$#" -ne 2 ]; then
        echo "pbindex_dir indir (contain bam files) logdir"
        exit 0
fi

indir=$1
logdir=$2

bamfiles=$(ls $indir/*.bam)

for bamfile in $bamfiles; do
	samplename=$(basename $bamfile)
	cmd="submitjob -w 1 -c 1 -m 8 -j $samplename -o $logdir pbindex $bamfile"
	$cmd
done

