#!/bin/bash
if [ "$#" -ne 4 ]; then
        echo "pbmm2_align inbamfile outbamfile reffile nthread"
        exit 0
fi

inbamfile=$1
outbamfile=$2
reffile=$3
nthread=$4


echo "inbamfile=$inbamfile"
echo "outbamfile=$outbamfile"
echo "reffile=$reffile"
echo "nthread=$nthread"


pbmm2 align $reffile $inbamfile $outbamfile".pbmm5.tmp.bam" -j $nthread -l 1000

samtools view --threads $nthread -b -F 4079 $outbamfile".pbmm5.tmp.bam" > $outbamfile".unsorted.bam"
rm $outbamfile".pbmm5.tmp.bam"

samtools sort --threads $nthread -T $outbamfile".sort.tmp" -o $outbamfile $outbamfile".unsorted.bam"
rm $outbamfile".unsorted.bam"

samtools index $outbamfile



