#!/bin/bash
if [ "$#" -ne 5 ]; then
        echo "pbmm2_align_dir indir outdir reffile nthread logdir"
        exit 0
fi

indir=$1
outdir=$2
reffile=$3
nthread=$4
logdir=$5

mkdir -p $outdir
for bamfile in $(ls $indir | grep ".bam$" ); do
	submitjob -w 8 -c $nthread -m 8 -o $logdir -j $bamfile pbmm2_align $indir/$bamfile $outdir/$bamfile $reffile $nthread
done


