#!/bin/bash
if [ "$#" -ne 5 ]; then
        echo "pbvariantcaller_dir indir (output of pbalign_dir) reffile outdir nthread logdir"
        exit 0
fi

indir=$1
reffile=$2
outdir=$3
nthread=$4
logdir=$5

mkdir -p $outdir

for bamfile in $(ls $indir/*.bam); do
	samplename=$(basename $bamfile)
	samplename=${samplename%.*}
	
	gff_file=$outdir/$samplename.gff
	fa_file=$outdir/$samplename.fasta
	fq_file=$outdir/$samplename.fastq
	
	cmd="submitjob -w 4 -c $nthread -m 16 -o $logdir -j $samplename variantCaller -j $nthread -r $reffile -o $gff_file -o $fa_file -o $fq_file $bamfile"
		
	$cmd
done


#mkdir -p $3

#ls $1 | egrep "*.bam$" | awk -v indir=$1 -v reffile=$2 -v outdir=$3 -v hpcopt="submitjob 16 -c 4 -m 16 -P acc_LymeMIND -q premium" '{cmd=hpcopt" variantCaller -j 4 "indir"/"$0" -r "reffile;gsub(".bam","",$0);cmd=cmd" -o "outdir"/"$0".gff"" -o "outdir"/"$0".fasta"" -o "outdir"/"$0".fastq"; print cmd; system(cmd)}'




