#!/bin/bash
if [ "$#" -ne 3 ]; then
        echo "pileup_exclude_loci loci_list pileup_file out_file"
        exit 0
fi

loci_list=$1
pileup_file=$2
out_file=$3

awk -F "\t" '{
	if (NR==FNR){
		methyl_loci[$1]=1
	}else{
		if (methyl_loci[$1]!=1){
			print
		}
	}
	
}' $loci_list $pileup_file > $out_file









