#!/bin/bash
if [ $# -ne 6 ] ; then
        echo "qc_fastq_stat_dir indir(fastq files) outdir nthread nreads minqv logdir"
        exit 0
fi

indir=$1
outdir=$2
nthread=$3
nreads=$4
minqv=$5
logdir=$6

mkdir -p $outdir
mkdir -p $logdir

for fastqfile in $(ls $indir | grep .fastq$); do
	cur_outdir=$outdir/${fastqfile%.*}
	submitjob -w 4 -c $nthread -m 16 -j ${fastqfile%.*} -o $logdir qc_fastq_stat $indir/$fastqfile $cur_outdir $nthread $nreads $minqv
done






