#!/bin/bash
if [ $# -ne 4 ] ; then
        echo "qc_fastq_stat_dir indir(fastq files) outdir nthread nreads"
        exit 0
fi

indir=$1
outdir=$2
nthread=$3
nreads=$4

mkdir -p $outdir

for fastqfile in $(ls $indir | grep .fastq$); do
	cur_outdir=$outdir/${fastqfile%.*}
	submitjob 4 -c $nthread -m 16 -P acc_LymeMIND -q premium qc_fastq_stat $indir/$fastqfile $cur_outdir $nthread $nreads
	#cmd="qc_fastq_stat $indir/$fastqfile $cur_outdir $nthread $nreads"
	#echo $cmd
done




#fastp --reads_to_process $nreads --thread $nthread --disable_adapter_trimming --disable_trim_poly_g --qualified_quality_phred 8 --unqualified_percent_limit 50 --trim_front1 75 --trim_tail1 200 --length_required 1275 --length_limit 65534 -i $fastq_file -o $outdir/reads_filtered.fastq --json $outdir/reads_filtered.json --html $outdir/reads_filtered.html


