#!/bin/bash
[ $# -ge 1 -a -f "$1" ] && input="$1" || input="-"

sort -n $input | awk -v b=50 'BEGIN{n=0;}{
	n+=1
	x[n]=$1
}END{
	step = int(n/(b-1))
	for (i=0;i<(b-1);i++){
		print x[1 + i*step]
	}
	print x[n]
}'



