#!/bin/bash
if [ "$#" -ne 2 ] && [ "$#" -ne 3 ]; then
        echo "recode_dir indir logdir"
	echo "or"
	echo "recode_dir indir varfile logdir"
        exit 0
fi

m5files=$(ls $1/*.m5)

#hpcopt="submitjob 2 -c 1 -m 8 -P acc_LymeMIND -q premium"
#hpcopt=""
if [ "$#" -eq 2 ]; then
	for m5file in $m5files
	do
		varfile=${m5file%.*}.var
		recodefile=${m5file%.*}.recode
	       	cmd=$hpcopt" igda recode -f $m5file $varfile $recodefile"
	       	echo $cmd
		$cmd
	done
fi

if [ "$#" -eq 3 ]; then
	varfile=$2
	for m5file in $m5files
        do
                recodefile=${m5file%.*}.recode
		jobname=$(basename ${m5file%.*})
                submitjob -w 2 -c 1 -m 8 -o $3 -j $jobname igda recode $m5file $varfile $recodefile
		#cmd=$hpcopt" igda recode $m5file $varfile $recodefile"
                #echo $cmd
                #$cmd
        done
fi

