#!/bin/bash
if [ $# -ne 2 ] ; then
        echo "rename_canu_contig_dir indir outdir"
        exit 0
fi

mkdir -p $2

ls -d $1/*/ | awk -v indir=$1 -v outdir=$2 '{folder=$0; gsub(indir,"",folder); gsub("/","",folder);cmd="rename_canu_contig "$0"/"folder".contigs.fasta"" "outdir"/"folder".fasta"; print cmd; system(cmd)}'

#ls -d $1/*/ | awk -v indir=$1 -v outdir=$2 -v hpcopt="submitjob 4 -c 1 -m 6 -P acc_LymeMIND -q premium" '{cmd=hpcopt" filter_pacbio "$0" "outdir"/";gsub(indir"/","",$0); gsub("/","",$0); cmd=cmd$0".bam";  print cmd; system(cmd)}'

