#!/bin/bash
if [ $# -ne 3 ]; then
	echo "USAGE: sam2bam_dir indir nthread logdir"
	exit 0
fi

indir=$1
nthread=$2
logdir=$3
samfile_list=$(ls $indir/*.sam)

mkdir -p $logdir

for samfile in $samfile_list
do
	jobname=$(basename $samfile)
	jobname=${jobname%.*}
	submitjob -w 4 -c $nthread -m 16 -j $jobname -o $logdir sam2bam $samfile $nthread
done


