#!/bin/bash
walltime=4
memory=16
queue="premium"
while getopts ":hw:m:q:" opt; do
        case ${opt} in
                h )
                        echo "USAGE: sam2bam_dir -q queue -w walltime -m memory indir nthread logdir"
			echo "default:"
                        echo -e "\t-w 4"
			echo -e "\t-m 16"
			echo -e "\t-q premium"
			exit 0;;
                w )
                        walltime=$OPTARG;;
		m )
			memory=$OPTARG;;
		q )
			queue=$OPTARG;;
        	\? )
                        echo "Invalid option: $OPTARG" 1>&2;;
                : )
                        echo "Invalid option: $OPTARG requires an argument" 1>&2;;
        esac
done
shift $((OPTIND - 1))

if [ $# -ne 3 ]; then
	echo "USAGE: sam2bam_dir -q queue -w walltime -m memory indir nthread logdir"
        echo "default:"
        echo -e "\t-w 4"
        echo -e "\t-m 16"
	echo -e "\t-q premium"
	exit 0
fi

indir=$1
nthread=$2
logdir=$3
samfile_list=$(ls $indir/*.sam)

mkdir -p $logdir

for samfile in $samfile_list
do
	jobname=$(basename $samfile)
	jobname=${jobname%.*}
	submitjob -q $queue -w $walltime -c $nthread -m $memory -j $jobname -o $logdir sam2bam $samfile $nthread
done


