#!/bin/bash
if [ $# -ne 2 ]; then
	echo "USAGE: sam2bam samfile nthread"
	exit 0
fi

samfile=$1
nthread=$2

bamfile_unsorted=${samfile%.*}.unsorted.bam
bamfile=${samfile%.*}.bam 
tmpfile=$samfile.tmp

echo "bamfile is $bamfile"

samtools view --threads $nthread -h -b -o $bamfile_unsorted $samfile
samtools sort --threads $nthread -T $tmpfile -o $bamfile $bamfile_unsorted
samtools index $bamfile
rm $bamfile_unsorted


