#!/bin/bash
walltime=4
memory=16
queue="premium"
while getopts ":hw:m:q:" opt; do
        case ${opt} in
                h )
                        echo "USAGE: sam2bam_dir -q queue -w walltime -m memory indir outdir minqv logdir"
			echo "default:"
                        echo -e "\t-w 4"
			echo -e "\t-m 16"
			echo -e "\t-q premium"
			exit 0;;
                w )
                        walltime=$OPTARG;;
		m )
			memory=$OPTARG;;
		q )
			queue=$OPTARG;;
        	\? )
                        echo "Invalid option: $OPTARG" 1>&2;;
                : )
                        echo "Invalid option: $OPTARG requires an argument" 1>&2;;
        esac
done
shift $((OPTIND - 1))

if [ $# -ne 4 ]; then
	echo "USAGE: sam2bam_dir -q queue -w walltime -m memory indir outdir minqv logdir"
        echo "default:"
        echo -e "\t-w 4"
        echo -e "\t-m 16"
	echo -e "\t-q premium"
	exit 0
fi

indir=$1
outdir=$2
minqv=$3
logdir=$4
samfile_list=$(ls $indir/*.sam)

mkdir -p $logdir
mkdir -p $outdir

for samfile in $(ls $indir/*.sam); do
	samplename=$(basename $samfile)
	samplename=${samplename%.*}
        outfile="$outdir/$samplename.sam"
	cmd="submitjob -w $walltime -m $memory -q $queue -j $samplename -o $logdir sam_maskqv $samfile $outfile $minqv 1"
	$cmd
done	


