#!/bin/bash
if [ $# -ne 2 ]; then
	echo "USAGE: sam_addtag samfile tagfile"
	exit 0
fi

samfile=$1
tagfile=$2

samtools view -H $samfile
samtools view $samfile > $samfile.tmp.sam_addtag

awk '{
	if (NR == FNR){
		tag[$1] = $2
	}else{
		if (tag[$1] != ""){
			print $0"\t"tag[$1]
		}
	}

}' $tagfile $samfile.tmp.sam_addtag

rm $samfile.tmp.sam_addtag

