#!/bin/bash
if [ "$#" -ne 3 ]; then
        echo "samtom5_dir indir reffile logdir"
        exit 0
fi

indir=$1
reffile=$2
logdir=$3


for samfile in $(ls $indir | egrep ".sam$"); do
	jobname=${samfile%.*}
	submitjob -w 2 -c 1 -m 6 -o $logdir -j $jobname igda samtom5 $indir/$samfile $reffile $indir/$jobname.m5
done


#ls $1 | egrep ".sam$" | awk -v hpcopt="submitjob 2 -c 1 -m 6 -P acc_LymeMIND -q premium" -v indir=$1 -v reffile=$2 '{cmd=hpcopt" igda samtom5 "indir"/"$0" "reffile; gsub(".sam",".m5",$0); cmd=cmd" "indir"/"$0; print cmd; system(cmd)}'

#ls $1 | egrep ".sam$" | awk -v indir=$1 -v reffile=$2 '{cmd="igda samtom5 "indir"/"$0" "reffile; gsub(".sam",".m5",$0); cmd=cmd" "indir"/"$0; print cmd; system(cmd)}'





