#!/bin/bash
if [ "$#" -ne 2 ]; then
        echo "samtom5_dir indir reffile"
        exit 0
fi

ls $1 | egrep ".sam$" | awk -v hpcopt="submitjob 2 -c 1 -m 6 -P acc_LymeMIND -q premium" -v indir=$1 -v reffile=$2 '{cmd=hpcopt" igda samtom5 "indir"/"$0" "reffile; gsub(".sam",".m5",$0); cmd=cmd" "indir"/"$0; print cmd; system(cmd)}'





#if [ "$#" -eq 4 ] ; then
#	cat $4 | awk -v indir=$1 -v refile=$2 -v outdir=$3 -v hpcopt="submitjob 2 -c 8 -m 6 -P acc_LymeMIND -q premium" '{cmd=hpcopt" pbalign --minLength=1000 --minAccuracy=75 --algorithm=\"blasr\" --algorithmOptions=\"--clipping hard --bestn 1\" "indir"/"$0".bam "refile" "outdir"/"$0".bam" ; print cmd; system(cmd) }'
#fi


