#!/bin/bash
if [ "$#" -ne 2 ]; then
        echo "split_bam_by_ref samfile(or bam) outdir"
        exit 0
fi

mkdir -p $2
samtools view $1 | awk -F "\t" -v outdir=$2 '{
	outfile=$3
	gsub("\\|", "_", outfile);
	outpath=outdir"/"outfile".sam.tmp"
	print $0 > outpath;
}'


for samtmpfile in $(ls $2/*.sam.tmp);do
	samfile=${samtmpfile%.tmp}
	samplename=$(basename $samfile)
	samplename=${samplename%.sam}
	samtools view -H $1 | grep @SQ | grep $samplename > $samfile
	samtools view -H $1 | grep @PG >> $samfile
	cat $samtmpfile >> $samfile
	rm $samtmpfile
done

