#!/bin/bash
if [ $# -ne 5 ] ; then
        echo "trim_bam_by_region bamfile outfile chr start end(1-based)"
        exit 0
fi

bamfile=$1
outfile=$2
chr=$3
start_locus=$4
end_locus=$5

sam_region=$chr":"$start_locus"-"$end_locus

samtools view -H $bamfile | egrep "@PG|SN:$chr" > $outfile
samtools view $bamfile $sam_region | awk -F "\t" -v chr=$chr -v start_locus=$start_locus -v end_locus=$end_locus '
	function parse_cigar(cigar_str, cigar_num, cigar_type){
		delete cigar_num;
                delete cigar_type;
		split(cigar_str,cigar_num,"(M|I|D|N|S|H|P|=|X)");
		cigar_str_len = length(cigar_str);		
		k = 1;
		for (i=1; i<=cigar_str_len; i++){
			cur_char = substr(cigar_str,i,1);
			if (cur_char ~ /(M|I|D|N|S|H|P|=|X)/){
				cigar_type[k] = cur_char;
				k++;
			}
		}
	}	
	{
		parse_cigar($6, cigar_num, cigar_type); 

		if (length(cigar_num)-1 != length(cigar_type)){
			print "length(cigar_num)-1 != length(cigar_type)";
			print "length(cigar_num)-1 = " length(cigar_num)-1;
			print "length(cigar_type) = " length(cigar_type);
			print "NR = "NR;
			print "cigar_str = " $6;
			exit 1;
		}
		if (length(cigar_type)==0){
			print "empty cigar at record "NR;
			exit 1;
		}	
		# cut overhang region on the left
		cur_locus = $4;
		cigar_new="";
		left_clip=0;
		right_clip=0;
		for (i=1; i <= length(cigar_type); i++){
			is_moved = 0;
			if (cigar_type[i]=="M" || cigar_type[i]=="D" || cigar_type[i]=="N" || 
				cigar_type[i]=="=" || cigar_type[i]=="X"){
				cur_locus += cigar_num[i];
				is_moved = 1;
			}
			if (cur_locus > start_locus){
				if (cur_locus - 1 <= end_locus){
					if (is_moved){
						if (cur_locus - cigar_num[i] <= start_locus){
							cigar_new = cigar_new""(cur_locus - start_locus);
							if (cigar_type[i]=="M" || cigar_type[i]=="I" || cigar_type[i]=="S" || cigar_type[i]=="=" || cigar_type[i]=="X"){
								left_clip += (start_locus - (cur_locus - cigar_num[i]) )
							}
						}else{
							cigar_new = cigar_new""cigar_num[i];
						}
					}else{
						cigar_new = cigar_new""cigar_num[i];
					}
					cigar_new = cigar_new""cigar_type[i]
				}else{
					if (cur_locus - 1 - cigar_num[i] < end_locus){
						cigar_new = cigar_new""(end_locus - (cur_locus-cigar_num[i]) + 1)
						cigar_new = cigar_new""cigar_type[i]
						if (cigar_type[i]=="M" || cigar_type[i]=="I" || cigar_type[i]=="S" || cigar_type[i]=="=" || cigar_type[i]=="X"){
							right_clip += cur_locus - 1 - end_locus
						}
					}else{
						if (cigar_type[i]=="M" || cigar_type[i]=="I" || cigar_type[i]=="S" || cigar_type[i]=="=" || cigar_type[i]=="X"){
							right_clip += cigar_num[i]
						}
					}
				}
			}else{
				# if cur_locus <= start_locus add soft clips to the left side of cigar
				if (cigar_type[i]=="M" || cigar_type[i]=="I" || cigar_type[i]=="S" || cigar_type[i]=="=" || cigar_type[i]=="X"){
					left_clip += cigar_num[i]	
				}
			}
		}
		
		# add soft clips
		if (left_clip>0){
			cigar_new = left_clip"S"cigar_new
		}
		if (right_clip>0){
			cigar_new = cigar_new""right_clip"S"
		}
		
		$6 = cigar_new
		if ($4 < start_locus){
			$4 = start_locus
		}
		
		new_record = "";
		for (i = 1; i<= (NF-1); i++){
			new_record = new_record""$i"\t"
		}
		new_record = new_record""$i
		print new_record
	}
' >> $outfile 



